name: Slack Notification

on: [push]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: |
          echo "Test"
          exit 1

      # 参考資料
      # - Slack が提供する GitHub Action "slack-send" を使って GitHub から Slack に通知する - Qiita
      #     https://qiita.com/seratch/items/28d09eacada09134c96c
      # - GitHub Actionsで1つ以上のジョブが失敗した場合にSlackに通知する
      #     https://zenn.dev/ntoy/articles/3e7521cd39a75b
      - name: Failure Notification
        if: failure()
        uses: slackapi/slack-github-action@v1.21.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":github: ビルド結果: ${{ job.status }}"
                  }
                },
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "mrkdwn",
                      "text": "Author: <https://github.com/${{ github.event.sender.login }}|@${{ github.event.sender.login }}>"
                    }
                  ]
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "結果を確認",
                        "emoji": true
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}